# Generated by Django 5.2.2 on 2025-06-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro / Não informar')], max_length=1)),
                ('contatos_parentes', models.TextField(blank=True)),
                ('doencas', models.TextField(blank=True, help_text='Doenças pré-existentes')),
                ('condicoes', models.TextField(blank=True, help_text='Condições especiais ou alergias')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('unidade_medida', models.CharField(help_text='Ex: mg, ml, comprimido', max_length=20)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdministracaoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_previsto', models.DateTimeField()),
                ('foi_administrado', models.BooleanField(default=False)),
                ('nao_tomou_motivo', models.CharField(blank=True, help_text='Preencher se o idoso não tomou o medicamento (NT)', max_length=255, null=True)),
                ('data_hora_administracao', models.DateTimeField(blank=True, help_text='Horário exato em que foi administrado', null=True)),
                ('enfermeiro_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='api.idoso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.medicamento')),
            ],
            options={
                'verbose_name': 'Administração de Medicamento',
                'verbose_name_plural': 'Administrações de Medicamentos',
                'ordering': ['horario_previsto'],
            },
        ),
    ]
