# Generated by Django 5.2.3 on 2025-06-21 18:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='endereço de e-mail')),
                ('nome_completo', models.CharField(blank=True, max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da casa de idosos', max_length=100, unique=True, verbose_name='Nome do Grupo')),
                ('senha_hash', models.CharField(max_length=128)),
                ('codigo_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Acesso do Grupo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Grupo')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização do Grupo')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_administrados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador do Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Idoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro / Não informar')], max_length=1, verbose_name='Gênero')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, verbose_name='RG')),
                ('cartao_sus', models.CharField(max_length=20, verbose_name='Cartão Nacional de Saúde (CNS)')),
                ('possui_plano_saude', models.BooleanField(default=False, verbose_name='Possui plano de saúde?')),
                ('plano_saude', models.CharField(blank=True, choices=[('BRA', 'Bradesco Saúde'), ('UNI', 'Unimed'), ('SUL', 'Sul América Saúde'), ('AMI', 'Amil Saúde'), ('NOT', 'NotreDame Intermédica'), ('OUT', 'Outro')], max_length=3, null=True, verbose_name='Plano de Saúde')),
                ('plano_saude_outro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual outro plano?')),
                ('numero_carteirinha_plano', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Carteirinha (Plano de Saúde)')),
                ('doencas', models.TextField(blank=True, help_text='Doenças pré-existentes', verbose_name='Doenças')),
                ('condicoes', models.TextField(blank=True, help_text='Condições especiais ou alergias', verbose_name='Condições')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idosos_da_casa', to='api.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoParente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Parente')),
                ('parentesco', models.CharField(choices=[('FI', 'Filho(a)'), ('NE', 'Neto(a)'), ('IR', 'Irmão(ã)'), ('PA', 'Pai/Mãe'), ('AV', 'Avô/Avó'), ('OU', 'Outro')], max_length=2, verbose_name='Parentesco')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='api.idoso')),
            ],
            options={
                'verbose_name': 'Contato de Parente',
                'verbose_name_plural': 'Contatos de Parentes',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(help_text='Nome comercial do medicamento. Se for genérico, pode repetir o princípio ativo.', max_length=200, unique=True, verbose_name='Nome')),
                ('principio_ativo', models.CharField(blank=True, max_length=200, verbose_name='Princípio Ativo')),
                ('generico', models.BooleanField(default=False, verbose_name='É Genérico?')),
                ('fabricante', models.CharField(blank=True, max_length=100, verbose_name='Fabricante/Laboratório')),
                ('concentracao_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Concentração (Valor)')),
                ('concentracao_unidade', models.CharField(blank=True, choices=[('mcg/g', 'mcg/g'), ('mg/g', 'mg/g'), ('mg/ml', 'mg/ml'), ('UN', 'Unidade'), ('OUT', 'Outro')], max_length=5, null=True, verbose_name='Unidade de Concentração')),
                ('forma_farmaceutica', models.CharField(choices=[('COMP', 'Comprimido'), ('CAP', 'Cápsula'), ('LIQ_ML', 'Líquido (ml)'), ('CREME_G', 'Creme (g)'), ('GOTA', 'Gota'), ('OUT', 'Outro')], max_length=10, verbose_name='Forma Farmacêutica')),
                ('quantidade_estoque', models.PositiveIntegerField(default=0, help_text='Número de caixas/frascos em estoque.', verbose_name='Quantidade em Estoque (Embalagens)')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='api.grupo')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=10)),
                ('grupos', models.ManyToManyField(blank=True, related_name='membros', to='api.grupo', verbose_name='Grupos do Usuário')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='cuidadores', to='api.idoso', verbose_name='Idosos Responsáveis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('DI', 'Diária'), ('SE', 'Semanal'), ('ME', 'Mensal'), ('EV', 'Eventual')], default='DI', max_length=2, verbose_name='Frequência da Dose')),
                ('dia_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('dia_segunda', models.BooleanField(default=False, verbose_name='Segunda-feira')),
                ('dia_terca', models.BooleanField(default=False, verbose_name='Terça-feira')),
                ('dia_quarta', models.BooleanField(default=False, verbose_name='Quarta-feira')),
                ('dia_quinta', models.BooleanField(default=False, verbose_name='Quinta-feira')),
                ('dia_sexta', models.BooleanField(default=False, verbose_name='Sexta-feira')),
                ('dia_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('horario_previsto', models.TimeField(verbose_name='Horário da Dose')),
                ('dosagem', models.CharField(help_text='Ex: 1 comprimido, 5ml, 2 gotas', max_length=100)),
                ('instrucoes', models.TextField(blank=True, help_text='Ex: Administrar com alimentos.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para suspender esta prescrição.')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes', to='api.idoso')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.medicamento')),
            ],
            options={
                'verbose_name': 'Prescrição',
                'verbose_name_plural': 'Prescrições',
                'ordering': ['horario_previsto'],
            },
        ),
        migrations.CreateModel(
            name='LogAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_administracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Administração')),
                ('status', models.CharField(choices=[('OK', 'Administrado'), ('REC', 'Recusado pelo paciente'), ('PUL', 'Pulado/Esquecido')], default='OK', max_length=3)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_de_administracao', to='api.prescricao')),
            ],
        ),
        migrations.AddConstraint(
            model_name='idoso',
            constraint=models.UniqueConstraint(fields=('grupo', 'cpf'), name='unique_cpf_por_grupo'),
        ),
        migrations.AddConstraint(
            model_name='idoso',
            constraint=models.UniqueConstraint(fields=('grupo', 'rg'), name='unique_rg_por_grupo'),
        ),
        migrations.AddConstraint(
            model_name='idoso',
            constraint=models.UniqueConstraint(fields=('grupo', 'cartao_sus'), name='unique_sus_por_grupo'),
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(fields=('grupo', 'nome_marca', 'principio_ativo', 'concentracao_valor', 'concentracao_unidade'), name='unique_medicamento_no_grupo'),
        ),
    ]
