# Generated by Django 5.2.2 on 2025-06-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idoso',
            name='contatos_parentes',
        ),
        migrations.AlterField(
            model_name='idoso',
            name='condicoes',
            field=models.TextField(blank=True, help_text='Condições especiais ou alergias', verbose_name='Condições'),
        ),
        migrations.AlterField(
            model_name='idoso',
            name='doencas',
            field=models.TextField(blank=True, help_text='Doenças pré-existentes', verbose_name='Doenças'),
        ),
        migrations.AlterField(
            model_name='idoso',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro / Não informar')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='ContatoParente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Parente')),
                ('parentesco', models.CharField(choices=[('FI', 'Filho(a)'), ('NE', 'Neto(a)'), ('CO', 'Cônjuge'), ('SO', 'Sobrinho(a)'), ('OU', 'Outro')], max_length=2, verbose_name='Parentesco')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='api.idoso')),
            ],
            options={
                'verbose_name': 'Contato de Parente',
                'verbose_name_plural': 'Contatos de Parentes',
            },
        ),
    ]
