# Generated by Django 5.2.3 on 2025-06-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='dosagem',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='dose_unidade',
            field=models.CharField(default='un', help_text='Ex: mg, ml, comprimido, gota, etc.', max_length=20, verbose_name='Unidade da Dose'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='dose_valor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Ex: 1.5 para 1,5 comprimidos ou 10 para 10ml', max_digits=10, verbose_name='Valor da Dose'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade_estoque',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantidade de embalagens disponíveis no estoque. Ex: 10 comprimidos, 5 frascos de 100ml, etc.', max_digits=10, verbose_name='Quantidade em Estoque (Embalagens)'),
        ),
    ]
