# Generated by Django 5.2.2 on 2025-06-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.RemoveConstraint(
            model_name='medicamento',
            name='unique_medicamento_por_grupo',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentracao_unidade',
            field=models.CharField(blank=True, choices=[('mcg/g', 'mcg/g'), ('mg/g', 'mg/g'), ('mg/ml', 'mg/ml'), ('OUT', 'Outro')], max_length=5, null=True, verbose_name='Unidade de Concentração'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='concentracao_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Concentração (Valor)'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fabricante/Laboratório'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('COMP', 'Comprimido'), ('CAP', 'Cápsula'), ('LIQ_ML', 'Líquido (ml)'), ('CREME_G', 'Creme (g)'), ('GOTA', 'Gota'), ('OUT', 'Outro')], default='OUT', max_length=10, verbose_name='Forma Farmacêutica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='generico',
            field=models.BooleanField(default=False, verbose_name='É Genérico?'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nome_marca',
            field=models.CharField(default='definir', help_text='Nome comercial do medicamento. Se for genérico, pode repetir o princípio ativo.', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='principio_ativo',
            field=models.CharField(default='definir', max_length=200, verbose_name='Princípio Ativo'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(fields=('grupo', 'nome_marca', 'principio_ativo', 'concentracao_valor', 'concentracao_unidade'), name='unique_medicamento_no_grupo'),
        ),
    ]
