# Generated by Django 5.2.3 on 2025-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='concentracao_unidade',
            field=models.CharField(blank=True, choices=[('mcg/g', 'mcg/g'), ('mg/g', 'mg/g'), ('mg/ml', 'mg/ml'), ('UN', 'Unidade'), ('OUT', 'Outro')], max_length=5, null=True, verbose_name='Unidade de Concentração'),
        ),
    ]
