# Generated by Django 5.2.2 on 2025-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_idoso_contatos_parentes_alter_idoso_condicoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoso',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='idoso',
            name='numero_carteirinha_plano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Carteirinha - Plano de Saúde'),
        ),
        migrations.AddField(
            model_name='idoso',
            name='plano_saude',
            field=models.CharField(blank=True, choices=[('BRA', 'Bradesco Saúde'), ('UNI', 'Unimed'), ('SUL', 'SulAmérica'), ('HAP', 'Hapvida'), ('OUT', 'Outro')], max_length=3, null=True, verbose_name='Plano de Saúde'),
        ),
        migrations.AddField(
            model_name='idoso',
            name='plano_saude_outro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qual outro plano?'),
        ),
        migrations.AddField(
            model_name='idoso',
            name='possui_plano_saude',
            field=models.BooleanField(default=False, verbose_name='Possui plano de saúde?'),
        ),
        migrations.AddField(
            model_name='idoso',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
    ]
