# Generated by Django 5.2.2 on 2025-06-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_medicamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoparente',
            name='parentesco',
            field=models.CharField(choices=[('FI', 'Filho(a)'), ('NE', 'Neto(a)'), ('IR', 'Irmão(ã)'), ('PA', 'Pai/Mãe'), ('AV', 'Avô/Avó'), ('OU', 'Outro')], max_length=2, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='idoso',
            name='plano_saude',
            field=models.CharField(blank=True, choices=[('BRA', 'Bradesco Saúde'), ('UNI', 'Unimed'), ('SUL', 'Sul América Saúde'), ('AMI', 'Amil Saúde'), ('NOT', 'NotreDame Intermédica'), ('OUT', 'Outro')], max_length=3, null=True, verbose_name='Plano de Saúde'),
        ),
    ]
