# Generated by Django 5.2.3 on 2025-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_prescricao_dosagem_prescricao_dose_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='dose_unidade',
            field=models.CharField(default='unidade(s)', help_text='Ex: mg, ml, comprimido, gota, etc.', max_length=20, verbose_name='Unidade da Dose'),
        ),
    ]
