# Generated by Django 5.2.3 on 2025-06-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_prescricao_dose_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescricoes_relacionadas', to='api.medicamento'),
        ),
    ]
