# Generated by Django 5.2.2 on 2025-06-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_idoso_cpf_idoso_numero_carteirinha_plano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoso',
            name='cartao_sus',
            field=models.CharField(default='pendente', max_length=20, verbose_name='Cartão Nacional de Saúde (CNS)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idoso',
            name='numero_carteirinha_plano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Carteirinha (Plano de Saúde)'),
        ),
    ]
