# Generated by Django 5.2.2 on 2025-06-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_idoso_cartao_sus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='unidade_medida',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem',
            field=models.CharField(default='pendente', help_text='Ex: 50mg, 5ml, 3 comprimidos', max_length=20),
            preserve_default=False,
        ),
    ]
