# Generated by Django 5.2.3 on 2025-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_prescricao_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='concentracao_unidade',
            field=models.CharField(blank=True, choices=[('mcg/g', 'mcg/g'), ('mg/g', 'mg/g'), ('mg/ml', 'mg/ml'), ('OUT', 'Outro')], max_length=5, null=True, verbose_name='Unidade de Concentração'),
        ),
    ]
