# Generated by Django 5.2.2 on 2025-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_medicamento_unidade_medida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='dosagem',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem_unidade',
            field=models.CharField(blank=True, choices=[('mg/g', 'mg/g'), ('mcg/g', 'mcg/g'), ('mg/ml', 'mg/ml')], max_length=5, null=True, verbose_name='Unidade da Dosagem'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='dosagem_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Dosagem'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(blank=True, choices=[('COMP', 'Comprimido'), ('CAP', 'Cápsula'), ('LIQ_ML', 'Líquido (ml)'), ('CREME_G', 'Creme (g)'), ('OUT', 'Outro')], max_length=10, null=True, verbose_name='Forma Farmacêutica'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='quantidade_por_embalagem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nº de comprimidos/cápsulas por caixa ou volume total em ml/g.', max_digits=10, null=True, verbose_name='Quantidade por Embalagem'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por Embalagem'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0, help_text='Número de caixas/frascos em estoque.', verbose_name='Quantidade em Estoque (Embalagens)'),
        ),
    ]
