# Generated by Django 5.2.2 on 2025-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_medicamento_dosagem_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoso',
            name='numero_carteirinha_plano',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número da Carteirinha (Plano de Saúde)'),
        ),
        migrations.AlterField(
            model_name='idoso',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG'),
        ),
    ]
