# Generated by Django 5.2.2 on 2025-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_idoso_numero_carteirinha_plano_alter_idoso_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoso',
            name='cartao_sus',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cartão Nacional de Saúde (CNS)'),
        ),
        migrations.AlterField(
            model_name='idoso',
            name='cpf',
            field=models.CharField(default='pendente', max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idoso',
            name='rg',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='RG'),
        ),
    ]
